services:
  ubuntu-novnc-pulseaudio:
    image: drlight17/ubuntu-novnc-pulseaudio:0.1
    container_name: ubuntu-novnc-pulseaudio
    ports:
      - "8099:10000"
    environment:
      - VNC_PASSWD=your_password_here
      - PORT=10000
      - AUDIO_PORT=1699
      - WEBSOCKIFY_PORT=6900
      - VNC_PORT=5900
      - SCREEN_WIDTH=1024
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24
    privileged: true
    shm_size: 1g
